[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.55.5"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

  [[redirects]]
  from = "/about"
  to = "/science/"
  status = 301
  force = false

  from = "/news"
  to = "/contact"
  status = 301
  force = false
  
  
